In [2]:
import numpy as np 

In [3]:
#创建ndarray数组
arr = np.array([1,2,3,4,5])
arr

array([1, 2, 3, 4, 5])

In [ ]:
#数组指定数据类型
a1 = np.array([1,2,3],float)
a1

array([1., 2., 3.])

In [ ]:
#创建多维数组
a2 = np.array([(1,2,3),(4,5,6),(7,8,9)])
a2

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [ ]:
#NumPy特殊数组创建
a3 = np.zeros((2,3),dtype = np.float32)    #两行散列的全0的float类型的数组
a3

array([[0., 0., 0.],
       [0., 0., 0.]], dtype=float32)

In [19]:
#3行3列的全为1的数组
b = np.ones((3,3))
b

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [ ]:
#创建等差数列，1开始5结束，0.5为差，且最后一项一定小于5
a4 = np.arange(1,5,0.5)
a4

array([1. , 1.5, 2. , 2.5, 3. , 3.5, 4. , 4.5])

In [ ]:
#创建单位矩阵
a5 = np.eye(3)
a5

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [23]:
#生产指定长度的，在【0，1）之间平均分布的随机数组
np.random.random(5)

array([0.38013684, 0.59520708, 0.32562738, 0.03807835, 0.96646076])

In [24]:
np.random.random(8)

array([0.08279291, 0.8946088 , 0.77233792, 0.78818823, 0.17130351,
       0.12457105, 0.13560916, 0.36275978])

In [25]:
#生产指定长度，符合正态分布的随机数组，均值0，标准差0.1
mu,sigma =0,0.1
np.random.normal(mu,sigma,5)

array([ 0.02720212, -0.1809118 ,  0.00208176,  0.04213808, -0.00171918])

In [ ]:
#NumPy数组的访问，支持切片操作，我们可以切片每一个维度，索引每一个维度：
a6 = np.array([(1,2),(3,4),(5,6)])
a6[0]

array([1, 2])

In [ ]:
a7 = np.array([(1,2),(3,4),(5,6)])
a7[1:]

array([[3, 4],
       [5, 6]])

In [ ]:
a8 = np.array([(1,2),(3,4),(5,6)])
print(a8[:,1])   #（‘ ：’所有行）的第1列

[2 4 6]


In [ ]:
#NumPy数组的遍历
#一维数组的遍历
a9 = np.array([1,2,3])
for i in a9:
    print(i)

1
2
3


In [32]:
#多维数组的遍历
a10 = np.array([(1,2),(3,4),(5,6)])
for i,j in a10:
    print(i,j)

1 2
3 4
5 6


In [33]:
a11 = np.array([(1,2,3),(4,5,6),(7,8,9)])
print("ndim:",a11.ndim)     #数组的维度，等于秩
print("shape:",a11.shape)   #数组的大小
print("size",a11.size)      #数组元素的总个数
print("dtype",a11.dtype)    #数组中元素类型的对象

ndim: 2
shape: (3, 3)
size 9
dtype int32


In [35]:
#NumPy数组的基本操作
#1.检测数值是否在数组中
a12 = np.array([(1,2),(3,4)])
print(3 in a12)
print(5 in a12)

True
False


In [38]:
#数组的重排列reshape
a13 = np.zeros([2,3,4])
a13

array([[[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]]])

In [39]:
a13.reshape(24)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0.])

In [ ]:
a14 = np.arange(1,10)
print(a14)
print(a14.shape)

a14=a14.reshape(3,3,1)   #维度大小乘积 == 元素个数
print(a14)

print(a14.shape)        #高维矩阵，每个维度都有含义

[1 2 3 4 5 6 7 8 9]
(9,)
[[[1]
  [2]
  [3]]

 [[4]
  [5]
  [6]]

 [[7]
  [8]
  [9]]]
(3, 3, 1)


In [42]:
#转置（可以直接.T）tanspose
a15 = np.array([(1,2,3),(4,5,6),(7,8,9)])
a15.transpose()

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

In [ ]:
a16 = np.array([(1,2,3),(4,5,6),(7,8,9)])
a16 = a16.T
print(a16)
#还有一种方法，在PyTorch中实现

[[1 4 7]
 [2 5 8]
 [3 6 9]]


In [ ]:
#flatten：把多维数组转换为一维数组，注意每个元组的长度是相同的(神经网络中常用，flatten平面)
a17 = np.array([(1,2),(3,4),(5,6)])
a17.flatten()

array([1, 2, 3, 4, 5, 6])

In [49]:
#newaxis:增加维度
a18 = np.array([(1,2),(3,4),(5,6)])
a18 = a18[:,np.newaxis,:]
a18.shape

(3, 1, 2)

In [54]:
#加减乘除运算
#维度能够对应上
a19 = np.ones((2,2))
b19 = np.array([(-1,1),(-1,1)])
print(a19)
print(b19)
print()
print(a19+b19)
print()
print(a19-b19)

[[1. 1.]
 [1. 1.]]
[[-1  1]
 [-1  1]]

[[0. 2.]
 [0. 2.]]

[[2. 0.]
 [2. 0.]]


In [58]:
#求和，求积
a20 = np.array([1,2,1])
a20.sum()
a20.prod()

2

In [ ]:
#平均数，方差，标准差
a21 = np.array([5,3,1])
print("mean:",a21.mean())
print("var:",a21.var())
print("std:",a21.std())

mean: 3.0
var: 2.6666666666666665
std: 1.632993161855452


In [62]:
a22 = np.array([1.2,3.8,4.9])
print("argmax:",a22.argmax())   #最大值索引
print("argmin:",a22.argmin())   #最小值索引

print("ceil:",np.ceil(a22))       #向上取整
print("floor:",np.floor(a22))     #向下取整
print("rint:",np.rint(a22))       #四舍五入

argmax: 2
argmin: 0
ceil: [2. 4. 5.]
floor: [1. 3. 4.]
rint: [1. 4. 5.]


In [64]:
#排序sort
a23 = np.array([16,31,12,28,22,31,48])
a23.sort()
a23

array([12, 16, 22, 28, 31, 31, 48])