In [1]:
import numpy as np

In [2]:
a = np.array([[1,2,3],[4,5,6]])
b = np.array([[4,5,6],[7,8,9]])
a * b            #直接乘法，或者使用np.dot（x,y）进行矩阵乘法

array([[ 4, 10, 18],
       [28, 40, 54]])

In [3]:
#定义两个矩阵
m1 = np.array([[1,2],[3,4]],dtype=np.float32)
m2 = np.array([[5,6],[7,8]],dtype=np.float32)

#使用 np.dot 进行矩阵乘法
result_dot = np.dot(m1,m2)
result_at = m1 @ m2
print("矩阵 1：")
print(m1)
print("矩阵 2：")
print(m2)
print("使用np.dot得到的矩阵乘法结果：")
print(result_dot)
print("使用@得到的矩阵乘法结果：")
print(result_at)

#创建一个全零矩阵，用于存储手动推演的结果
#结果矩阵的行数等于 matrix1 的行数，列数等于 matrix2 的列数
manual_result = np.zeros((m1.shape[0],m2.shape[1]),dtype=np.float32)

#外层循环：遍历 matrix1 的每一行
# i 表示结果矩阵的行索引
for i in range(m1.shape[0]):
    # 中层循环：遍历 matrix2 的每一列
    # j 表示结果矩阵的列索引
    for j in range(m2.shape[1]):
        #初始化当前位置的结果为0
        manual_result[i,j] = 0
        # 内层循环：计算 matrix1 的第 i 行与 matrix2 的第 j 列对应元素的乘积之和
        # k 表示参与乘法运算的元素索引
        for k in range(m1.shape[1]):
           #打印当前正在计算的元素
           print(f"{m1[i,k]} * {m2[k,j]} = {m1[i,k] * m2[k,j]}")
           #将 matrix1 的第 i 行第 k 列元素与 matrix2 的第 k 行第 j 列元素相乘，并累加到结果矩阵的相应位置
           manual_result[i,j] += m1[i,k] * m2[k,j]
        #答应当前位置计算完成后的结果
        print(f"结果矩阵[{i+1},{j+1}]:{manual_result[i,j]}\n")

print("手动推演结果：")
print(manual_result)

矩阵 1：
[[1. 2.]
 [3. 4.]]
矩阵 2：
[[5. 6.]
 [7. 8.]]
使用np.dot得到的矩阵乘法结果：
[[19. 22.]
 [43. 50.]]
使用@得到的矩阵乘法结果：
[[19. 22.]
 [43. 50.]]
1.0 * 5.0 = 5.0
2.0 * 7.0 = 14.0
结果矩阵[1,1]:19.0

1.0 * 6.0 = 6.0
2.0 * 8.0 = 16.0
结果矩阵[1,2]:22.0

3.0 * 5.0 = 15.0
4.0 * 7.0 = 28.0
结果矩阵[2,1]:43.0

3.0 * 6.0 = 18.0
4.0 * 8.0 = 32.0
结果矩阵[2,2]:50.0

手动推演结果：
[[19. 22.]
 [43. 50.]]


In [13]:
#文件操作
np.save('result.npy',manual_result)

In [15]:
result_np = np.load('result.npy')
result_np

array([[19., 22.],
       [43., 50.]], dtype=float32)

In [16]:
#NumPy广播机制(如果形状不相同，自动实现形状改变)
a = np.array([5,6,7])
b = np.array([-1,-1,-1])
a + b

array([4, 5, 6])

In [ ]:
a = np.array([(1,2),(2,2),(3,3),(4,4)])    #shape(4,2)
b = np.array([-1,1])      #shape(2) -> shape(1,2) -> shape(4,2)    [[-1,-1],[-1,-1],[-1,-1],[-1,-1]]
# b 的维度对其（升维）(***升维规律：由低到高)
a + b

array([[0, 3],
       [1, 3],
       [2, 4],
       [3, 5]])