In [ ]:
import torch

data = torch.tensor([[1,2],[3,4]])     #tensor为张量
data

tensor([[1, 2],
        [3, 4]])

In [82]:
import numpy as np

np_array = np.array([[1,2],[3,4]])
data2 = torch.from_numpy(np_array)
data2

RuntimeError: Numpy is not available

In [84]:
#通过已知张量的维度，创建新张量
data3 = torch.zeros_like(data)
data3

tensor([[0, 0],
        [0, 0]])

In [85]:
data4 = torch.rand_like(data,dtype=torch.float)
data4

tensor([[0.3403, 0.2415],
        [0.6447, 0.4864]])

In [86]:
#使用随机张量或常量值
# shape 是张量维度的元组
shape = (2,3,)
rand_tensor = torch.rand(shape)
ones_tensor = torch.ones(shape)
zeros_tensor = torch.zeros(shape)

print(f"Random Tensor: \n {rand_tensor} \n")
print(f"Ones Tensor: \n {ones_tensor} \n")
print(f"Zeros Tensor: \n {zeros_tensor} \n")

Random Tensor: 
 tensor([[0.3623, 0.4007, 0.5323],
        [0.1524, 0.5801, 0.2606]]) 

Ones Tensor: 
 tensor([[1., 1., 1.],
        [1., 1., 1.]]) 

Zeros Tensor: 
 tensor([[0., 0., 0.],
        [0., 0., 0.]]) 



In [93]:
#基于现有tensor构建，但使用新值填充
m = torch.ones(5,3, dtype=torch.double)
n = torch.rand_like(m, dtype=torch.float)

#获取tensor的大小
print(m.size())    #torch.Size([5,3])

#均匀分布
print(torch.rand(5,3))
#标准正态分布
print(torch.randn(5,3))
#离散正态分布
print(torch.normal(mean=.0,std=1.0,size=(5,3)))
#线性间隔向量（返回一个1维向量，包含在区间start和end上均匀间隔约steps个点）
print(torch.linspace(start=1,end=10,steps=20))

torch.Size([5, 3])
tensor([[0.3904, 0.8876, 0.7532],
        [0.4839, 0.0856, 0.6305],
        [0.4642, 0.1548, 0.3140],
        [0.5587, 0.4141, 0.5330],
        [0.8850, 0.3434, 0.2067]])
tensor([[ 0.7933, -0.4088,  3.0105],
        [ 0.8883, -1.2336, -0.6253],
        [-0.4297,  0.1447,  0.7112],
        [-1.6950,  1.3173,  0.6047],
        [-0.3948,  1.4421,  1.0728]])
tensor([[-0.9789,  0.4802, -0.1899],
        [-0.3951,  0.4947, -1.3424],
        [ 0.0032,  0.4453,  0.1748],
        [ 0.6797,  0.0756,  1.8995],
        [ 0.7770,  0.7639,  0.4242]])
tensor([ 1.0000,  1.4737,  1.9474,  2.4211,  2.8947,  3.3684,  3.8421,  4.3158,
         4.7895,  5.2632,  5.7368,  6.2105,  6.6842,  7.1579,  7.6316,  8.1053,
         8.5789,  9.0526,  9.5263, 10.0000])


In [94]:
tensor = torch.rand(3,4)

print(f"Shape of tensor: {tensor.shape}")
print(f"Datatype of tensor: {tensor.dtype}")
print(f"Device tensor is stored on: {tensor.device}")

Shape of tensor: torch.Size([3, 4])
Datatype of tensor: torch.float32
Device tensor is stored on: cpu


In [96]:
#检测pytorch是否支持GPU
print(torch.cuda.is_available())

False


In [ ]:
tensor = torch.ones(4,4)
print('First row:', tensor[0])
print('First column:', tensor[:,0])
print('Last colum:', tensor[...,-1])     #[...,-1]表示取所有行中的最后一列
tensor[:,1] = 0
print(tensor)

First row: tensor([1., 1., 1., 1.])
First column: tensor([1., 1., 1., 1.])
Last colum: tensor([1., 1., 1., 1.])
tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]])


In [99]:
#张量的拼接
t1 = torch.cat([tensor,tensor,tensor], dim=1)
print(t1)
print(t1.shape)

tensor([[1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.],
        [1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.],
        [1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.],
        [1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.]])
torch.Size([4, 12])


In [ ]:
import torch
tensor = torch.arange(1,10,dtype=torch.float32).reshape(3,3)

#计算两个张量之间矩阵乘法的几种方式， y1, y2, y3 最后的值是一样的 dot
y1 = tensor @ tensor.T
y2 = tensor.matmul(tensor.T)
print(y1)
print(y2)

y3 = torch.rand_like(tensor)
torch.matmul(tensor,tensor.T,out=y3)
print(y3)

#PyTorch中也完全支持点积运算

tensor([[ 14.,  32.,  50.],
        [ 32.,  77., 122.],
        [ 50., 122., 194.]])
tensor([[ 14.,  32.,  50.],
        [ 32.,  77., 122.],
        [ 50., 122., 194.]])
tensor([[ 14.,  32.,  50.],
        [ 32.,  77., 122.],
        [ 50., 122., 194.]])


In [ ]:
#转换为python类型（求单一结构值）
agg = tensor.sum()
agg_item = agg.item()
print(agg_item, type(agg_item))

45.0 <class 'float'>


In [ ]:
#In-place操作（直接修改张量里面的内容）
tensor.add_(5)    #模型计算时，该方法不太推荐，因为会丢失历史记录
# tensor = tensor + 5
# tensor += 5
print(tensor)

tensor([[1., 2., 3.],
        [4., 5., 6.],
        [7., 8., 9.]])

In [104]:
import torch
from torchviz import make_dot

ModuleNotFoundError: No module named 'torchviz'